### PR TITLE
Feature/changes for oxog

### PR DESCRIPTION
**Pull request by SolomonShorser-OICR**
Started making some changes so that OxoG can submit BAM files with VCF files.

### CODE REVIEW

**Comment by briandoconnor** [comment]
Hey @SolomonShorser-OICR, a few comments:

* you can drop this print message: https://github.com/ICGC-TCGA-PanCancer/vcf-uploader/pull/18/files#diff-6710761cf5f67e1f39ecd14d591a0825R253
* you can drop this print message: https://github.com/ICGC-TCGA-PanCancer/vcf-uploader/pull/18/files#diff-6710761cf5f67e1f39ecd14d591a0825R267

That's pretty minor... looks like a few debug messages.

As for the approach, I *think* it will work however this is where you're likely to run into problems here:

* https://github.com/ICGC-TCGA-PanCancer/vcf-uploader/pull/18/files#diff-6710761cf5f67e1f39ecd14d591a0825R924
and
* https://github.com/ICGC-TCGA-PanCancer/vcf-uploader/pull/18/files#diff-6710761cf5f67e1f39ecd14d591a0825R926

So the file types of 'bam' and 'bai' are what was used for the BAM uploader:

https://github.com/ICGC-TCGA-PanCancer/Seqware-BWA-Workflow/blob/develop/workflow/scripts/gnos_upload_data.pl#L522

But I suspect that the "*vcf*" studies do not have BAM/BAI upload enabled.

So we're going to have to chat with Jonathan S. (have him try an upload that you rsync, he can ingest it into the icgc vcf test study).  And probably Michael Ainsworth if it turns out we need BAM uploads enabled for these studies.  

Another thing we could do is create new studies but that's probably disruptive for Junjun and Linda and also unnecessary.

**Comment by briandoconnor** [comment]
By the way, tomorrow send me a path to a directory with the results for a run of this and I'll take a look at the output and see if it looks OK.  Then I'll merge the pull request.

**Comment by briandoconnor** [comment]
Another thought, if we get really stuck, the vcf studies in GNOS support tarballs.  So we *could* upload mini-bams as tarballs, one per BAM/BAI pair.  Not ideal... just saying that could unblock us if we hit some wall with GNOS.

**Comment by SolomonShorser-OICR** [comment]
I spoke with Christina yesterday about the issue of uploading BAMs and BAIs to the VCF study. At first she was concerned, but she also raised the issue of uploading tarballs and thought that since those are uploaded OK, the BAMs/BAIs might not be a problem either. But we need to do an actual upload to verify this.

**Pull request merged**
